Refactoring banking system
DaniilYusha/refactoring pull request #1
Opened 2020-08-16 19:22 UTC by DaniilYusha

2020-08-17 12:17 UTC, Anastasiia04 reviewed
Seems nice!

2020-08-17 12:17 UTC, Anastasiia04 commented on entities/usual_card.rb
> +    tax(amount, sender_percent, sender_fixed)
the same def in base class?

2020-08-17 12:17 UTC, Anastasiia04 commented on entities/virtual_card.rb
> +  end
the same

2020-08-17 12:17 UTC, Anastasiia04 commented on modules/account_manager.rb
> +    end
seems the same
maybe leave only the def find_card and use find_card.nil?  if we need to check for a card exist?

2020-08-17 12:17 UTC, Anastasiia04 commented on modules/validator.rb
> +module Validator
we use this only in Account class?
maybe move this one def to class?

2020-08-17 12:52 UTC, vasivaas commented on entities/account.rb
> +  attr_accessor :errors
why attr_accessor? maybe you can change to attr_reader?

2020-08-17 12:56 UTC, vasivaas approved these changes
nice!

2020-08-17 15:27 UTC, DaniilYusha commented on entities/usual_card.rb
> +    tax(amount, sender_percent, sender_fixed)
@Anastasiia04 no, in BaseCard class I have methods like `put_money`, `send_money`, but here only tax calculation

2020-08-17 16:32 UTC, DaniilYusha commented on modules/account_manager.rb
> +    end
@Anastasiia04 ok, done

2020-08-17 16:32 UTC, DaniilYusha commented on entities/account.rb
> +  attr_accessor :errors
@vasivaas thanks, done

2020-08-17 16:41 UTC, vasivaas commented on modules/account_registrator.rb
> +  def login_input
name_input, login_input, password input are identical, differ only in the initial message, it is possible to make a unique method which will have 1 parameter - the initial message?

2020-08-17 16:49 UTC, vasivaas commented on modules/account_actions.rb
> +module AccountActions
maybe you can move this method to another module? i think creating a module for one method  is not a best practice

2020-08-17 16:50 UTC, vasivaas requested changes
🔥 !

2020-08-18 12:42 UTC, Anastasiia04 approved these changes
good job!

2020-08-18 13:44 UTC, vasivaas approved these changes
🚀

2020-08-23 20:18 UTC, kolyanjy approved these changes

2021-02-10 00:49 UTC, merged